# 会議室名
room_name: "会議室C"

# 温度閾値の差分(単位は℃。閾値そのものは含まない。0.25度刻み)
temperature_diff: 4
# 照度閾値(単位はルクス。閾値そのものは含まない。1ルクス刻み)
luminosity: 100

# 赤外線アレイセンサのマトリクスにおける、室内のデジタル機器の位置(v2から対応)
#例：[[3, 3],[3, 4],[4, 4],[4, 5]]
location_devices: [******]
# 例えば、location_devicesを[[3, 3],[7, 7]]と指定した際の、赤外線アレイセンサの測定結果が下記の場合、29.5度と29.0度は温度閾値を超えていても人間とはみなさない(人判定からは無視される)。
# [25.0, 24.5, 25.75, 24.5, 26.0, 25.75, 26.0, 25.0]
# [26.0, 25.75, 25.0, 24.25, 27.0, 26.5, 24.5, 26.0]
# [26.5, 26.25, 26.5, 25.75, 27.0, 26.75, 25.75, 25.5]
# [27.0, 28.25, 28.25, 29.5, 31.5, 29.25, 27.25, 25.5]
# [28.0, 29.25, 27.5, 28.75, 29.75, 29.0, 27.0, 27.25]
# [28.5, 29.75, 27.75, 28.0, 28.25, 28.25, 27.5, 28.75]
# [27.75, 27.5, 27.5, 26.5, 28.5, 27.75, 27.25, 26.75]
# [26.5, 26.25, 26.5, 27.25, 29.0, 29.25, 26.5, 29.0]

# cumulocity
c8y:
  host: "******"
  pageSize: "1"
  username: "******"
  password: "******"
  appkey: "******"
  # typeはRaspberry piがデータをアップロードする際にJSONの"type"属性にて指定している文字列のこと。例：DHT11_Measurement
  dht11Type: "******"
  tsl2561Type: "******"
  roboba043Type: "******"
  # fragmentTypeはRaspberry piがデータをアップロードする際にJSONの先頭にて指定している文字列のこと。例：DHT11_TemperatureMeasurement
  dht11FragmentType: "******"
  tsl2561FragmentType:  "******"
  roboba043FragmentType: "******"
 
# [Twitter版のみ]Twitterアカウント情報
twitter:
  consumer_key:        "******"
  consumer_secret:     "******"
  access_token:        "******"
  access_token_secret: "******"
  